insert into States(cultureID, code, state, sortrank) values('en-US', 'AB', 'Alberta',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'AK', 'Alaska',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'AL', 'Alabama',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'AR', 'Arkansas',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'AS', 'American Samoa',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'AZ', 'Arizona',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'BC', 'British Columbia',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'CA', 'California',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'CO', 'Colorado',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'CT', 'Connecticut',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'DC', 'District Of Columbia',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'DE', 'Delaware',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'FL', 'Florida',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'FM', 'Federated States Of Micronesia',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'GA', 'Georgia',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'GU', 'Guam',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'HI', 'Hawaii',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'IA', 'Iowa',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'ID', 'Idaho',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'IL', 'Illinois',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'IN', 'Indiana',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'KS', 'Kansas',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'KY', 'Kentucky',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'LA', 'Louisiana',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MA', 'Massachusetts',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MB', 'Manitoba',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MD', 'Maryland',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'ME', 'Maine',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MH', 'Marshall Islands',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MI', 'Michigan',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MN', 'Minnesota',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MO', 'Missouri',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MP', 'Northern Mariana Islands',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MS', 'Mississippi',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'MT', 'Montana',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NB', 'New Brunswick',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NC', 'North Carolina',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'ND', 'North Dakota',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NE', 'Nebraska',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NF', 'Newfoundland',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NH', 'New Hampshire',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NJ', 'New Jersey',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NM', 'New Mexico',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NS', 'Nova Scotia',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NT', 'Northwest Territories',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NV', 'Nevada',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'NY', 'New York',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'OH', 'Ohio',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'OK', 'Oklahoma',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'ON', 'Ontario',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'OR', 'Oregon',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'PA', 'Pennsylvania',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'PE', 'Prince Edward Island',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'PR', 'Puerto Rico',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'PW', 'Palau',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'QC', 'Quebec',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'RI', 'Rhode Island',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'SC', 'South Carolina',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'SD', 'South Dakota',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'SK', 'Saskatchewan',3)
insert into States(cultureID, code, state, sortrank) values('en-US', 'TN', 'Tennessee',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'TX', 'Texas',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'UT', 'Utah',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'VA', 'Virginia',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'VI', 'Virgin Islands',2)
insert into States(cultureID, code, state, sortrank) values('en-US', 'VT', 'Vermont',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'WA', 'Washington',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'WI', 'Wisconsin',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'WV', 'West Virginia',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'WY', 'Wyoming',1)
insert into States(cultureID, code, state, sortrank) values('en-US', 'YT', 'Yukon',3)
